"""Generated-photo regressions; the in-memory transport is not native acceptance."""
import copy
import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from registry import Registry, CurationError, digest
from presentation import card
import guided_review as guided
import worker


class MemoryNative:
    """Only replaces transport; production task building and collection run unchanged."""
    def __init__(self):
        self.tasks = {}
        self.posts = 0
        self.lose_response = False

    def ensure_projects(self):
        return {"group": 1, "field": 2, "relationship": 3}

    def import_task(self, project, task):
        key = task["data"]["curation"]["task_key"]
        old = next((t for t in self.tasks.values() if t["data"]["curation"]["task_key"] == key), None)
        if old:
            return old
        tid = len(self.tasks) + 1
        self.tasks[tid] = {**copy.deepcopy(task), "id": tid, "project": project, "annotations": []}
        return self.tasks[tid]

    def read_task(self, tid):
        return copy.deepcopy(self.tasks[tid])

    def request(self, method, path, payload=None):
        if path.startswith("/api/storages/"):
            return []
        if method == "POST" and path.endswith("/annotations/"):
            assert "completed_by" not in payload and "ground_truth" not in payload
            tid = int(path.split("/")[3])
            self.posts += 1
            annotation = {**copy.deepcopy(payload), "id": 100 + self.posts, "completed_by": 999,
                          "task": tid, "created_ago": "just now"}
            self.tasks[tid]["annotations"].append(annotation)
            if self.lose_response:
                self.lose_response = False
                raise ConnectionError("simulated lost response")
            return annotation
        raise AssertionError("unexpected transport call")


class GuidedTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="artvenn-guided-generated-")
        self.base = Path(self.temp.name)
        self.registry = Registry(self.base / "runtime")
        self.source = self.base / "generated"
        self.source.mkdir()
        from PIL import Image
        for i in range(4):
            Image.new("RGB", (70, 50), (i * 50, 60, 70)).save(self.source / f"synthetic-{i}.png")
        # Deliberately exercise the local classification branch using generated bytes.
        self.batch = self.registry.inspect(self.source, synthetic=False)
        self.aids = [r["id"] for r in self.registry.rows("SELECT id FROM assets ORDER BY relative_path")]
        with self.registry.db:
            for oid, assets in (("target", self.aids[:2]), ("source", self.aids[2:3]), ("unselected", self.aids[3:])):
                self.registry.db.execute("INSERT INTO objects VALUES(?,?,?)", (oid, self.batch, oid))
                self.registry.propose(self.batch, oid, "group", None, assets, assets, "a" * 64, "synthetic-test", "test")
        self.native = MemoryNative()
        self.patch = patch.object(worker, "ls", return_value=self.native)
        self.patch.start()

    def tearDown(self):
        self.patch.stop()
        self.registry.db.close()
        self.temp.cleanup()

    def start(self):
        view = guided.begin(self.registry, ["target", "source"], "local")
        session = guided.read(self.registry, view["id"], "local")
        draft = copy.deepcopy(session["draft"])
        for item, role in zip(draft["photos"], ("overview", "detail", "context")):
            item.update(destination="target", role=role)
        draft["fields"]["title"].update(action="set", value="Synthetic test inscription")
        draft["fields"]["object_form"].update(action="set", value="碑刻")
        return session, draft

    def confirm(self, session, draft):
        return guided.confirm(self.registry, {}, session, draft, session["revision"], True)

    def test_draft_does_not_change_facts_memberships_or_native_review(self):
        session, draft = self.start()
        baseline = digest(self.registry.export()["tables"])
        guided.save(self.registry, session, draft, 1)
        self.assertEqual(digest(self.registry.export()["tables"]), baseline)
        self.assertEqual(self.native.posts, 0)
        reloaded = guided.read(self.registry, session["id"], "local")
        self.assertEqual(reloaded["draft"], draft)
        self.assertEqual(reloaded["revision"], 2)

    def test_unknown_optional_shape_can_stay_absent_when_confirming_a_card(self):
        session,draft=self.start()
        draft['fields']['object_form'].update(action='skip',value='')
        view=self.confirm(session,draft)
        self.assertEqual(view['state'],'collected',view.get('error'))
        self.assertFalse(self.registry.rows("SELECT * FROM facts WHERE object_id='target' AND field='object_form'"))
        self.assertFalse(view['missing'])

    def test_explicit_confirmation_scoped_collection_roles_and_replay(self):
        session, draft = self.start()
        untouched = guided.snapshot(self.registry, ["unselected"])
        view = self.confirm(session, draft)
        self.assertEqual(view["state"], "collected", view.get("error"))
        self.assertEqual(view["progress"]["collected"], 4)
        self.assertEqual(len(card(self.registry.db, "target")["assets"]), 3)
        self.assertEqual(card(self.registry.db, "source")["assets"], [])
        self.assertEqual(card(self.registry.db, "source")["movedTo"], ["AV-0001"])
        links = self.registry.rows("SELECT asset_id,role FROM object_assets ORDER BY asset_id")
        self.assertEqual({r["role"] for r in links}, {"overview", "detail", "context"})
        self.assertEqual(guided.snapshot(self.registry, ["unselected"]), untouched)
        self.assertEqual(self.native.posts, 4)
        self.confirm(session, draft)
        self.assertEqual(self.native.posts, 4)
        self.assertEqual(len(self.registry.rows("SELECT * FROM decisions")), 4)
        self.assertEqual({r["model_revision"] for r in self.registry.rows("SELECT * FROM proposals WHERE kind='field'")}, {"human-entry/v1"})

    def test_response_loss_reconciles_before_retry_without_duplicate_post(self):
        session, draft = self.start()
        self.native.lose_response = True
        failed = self.confirm(session, draft)
        self.assertEqual(failed["state"], "submitting")
        self.assertEqual(failed["progress"]["collected"], 0)
        recovered = self.confirm(session, draft)
        self.assertEqual(recovered["state"], "collected", recovered.get("error"))
        self.assertEqual(self.native.posts, 4)

    def test_uncertain_submission_without_readback_never_resubmits(self):
        session, draft = self.start()
        self.native.lose_response = True
        self.confirm(session, draft)
        first = next(t for t in self.native.tasks.values() if t["annotations"])
        first["annotations"] = []  # Simulate an unavailable outcome, not a native delete.
        again = self.confirm(session, draft)
        self.assertEqual(again["error"], "NATIVE_SUBMISSION_OUTCOME_UNKNOWN")
        self.assertEqual(self.native.posts, 1)
        self.assertEqual(again["progress"]["collected"], 0)

    def test_native_edit_between_readback_and_collect_is_not_applied(self):
        session, draft = self.start()
        original_collect = worker.collect
        def race(*args, **kwargs):
            for task in self.native.tasks.values():
                if task["data"]["curation"]["review_kind"] == "field":
                    task["annotations"][0]["result"][-1]["value"]["text"] = ["Unconfirmed changed text"]
            return original_collect(*args, **kwargs)
        with patch.object(worker, "collect", side_effect=race):
            view = self.confirm(session, draft)
        self.assertEqual(view["state"], "submitted_waiting_collection")
        self.assertEqual(view["error"], "CONFIRMED_NATIVE_ANNOTATION_CHANGED")
        self.assertEqual(self.registry.rows("SELECT * FROM facts"), [])

    def test_scope_stale_and_confirmation_guards(self):
        session, draft = self.start()
        with self.assertRaisesRegex(CurationError, "EXPLICIT_REVIEW_CONFIRMATION"):
            guided.confirm(self.registry, {}, session, draft, 1, False)
        outside = copy.deepcopy(draft)
        outside["photos"][0]["assetId"] = self.aids[3]
        with self.assertRaisesRegex(CurationError, "PHOTO_SCOPE"):
            guided.save(self.registry, session, outside, 1)
        with self.registry.db:
            self.registry.propose(self.batch, "target", "field", "title", "Changed", self.aids[:1], "b" * 64, "test", "test")
        with self.assertRaisesRegex(CurationError, "PREVIEW_STALE"):
            self.confirm(session, draft)
        self.assertEqual(self.native.posts, 0)

    def test_required_manual_fields_and_synthetic_fence(self):
        session, draft = self.start()
        draft["fields"]["title"]["value"] = ""
        with self.assertRaisesRegex(CurationError, "FIELD_VALUE_REQUIRED"):
            self.confirm(session, draft)
        self.assertEqual(self.native.posts, 0)
        with self.assertRaisesRegex(CurationError, "MATERIAL_MISMATCH"):
            guided.read(self.registry, session["id"], "synthetic")

    def test_invalid_working_name_fails_before_native_submission(self):
        session, draft = self.start()
        draft["workingName"] = "Synthetic\u007f"
        with self.assertRaisesRegex(CurationError, "WORKING_NAME_INVALID"):
            self.confirm(session, draft)
        self.assertEqual(self.native.posts, 0)

    def test_package_scope_roles_lineage_and_required_explicit_media(self):
        session, draft = self.start()
        self.assertEqual(self.confirm(session, draft)["state"], "collected")
        choice = {"objectId": "target", "title": "Synthetic test inscription", "kind": "inscription", "media": []}
        with self.assertRaisesRegex(CurationError, "PUBLIC_MEDIA_SCOPE"):
            guided.prepare_package(self.registry, session, choice, True)
        choice["media"] = [{"assetId": aid, "position": i, "isRepresentative": i == 0} for i, aid in enumerate(self.aids[:3])]
        # The separate native acceptance runs the real Node validator.
        from subprocess import CompletedProcess
        receipt = CompletedProcess([], 0, '{"status":"PASS"}', '')
        actual_run = worker.subprocess.run
        def adapter_only(args, **kwargs):
            return receipt if any(str(a).endswith("adapter.mjs") for a in args) else actual_run(args, **kwargs)
        with patch.object(worker.subprocess, "run", side_effect=adapter_only):
            view = guided.prepare_package(self.registry, session, choice, True)
        self.assertEqual(view["state"], "package_prepared")
        self.assertEqual(guided.project(self.registry, guided.read(self.registry, session["id"], "local"))["packageChoice"], choice)
        prepared = json.loads((self.registry.root / "state/prepared-package.json").read_text())
        package = json.loads(Path(prepared["path"]).read_text())
        self.assertIs(package["synthetic"], False)
        local = package["objects"][0]["localAnnotations"]
        self.assertEqual(set(local["photoRoles"]), set(self.aids[:3]))
        self.assertEqual({v["originObjectId"] for v in local["photoRoles"].values()}, {"target", "source"})
        self.assertEqual(len(local["reviewDecisions"]), 4)
        self.assertTrue(all(Path(p).is_file() for p in local["annotationSnapshots"]))
        self.assertEqual(len(local["annotationSnapshots"]), 4)

    def test_saved_session_cannot_package_later_changed_decisions(self):
        session, draft = self.start()
        self.assertEqual(self.confirm(session, draft)["state"], "collected")
        with self.registry.db:
            self.registry.propose(self.batch, "target", "field", "title", "Later review", self.aids[:1], "b" * 64, "test", "test")
        self.assertTrue(guided.project(self.registry, session)["stale"])
        with self.assertRaisesRegex(CurationError, "PREVIEW_STALE"):
            guided.prepare_package(self.registry, session, {}, True)


if __name__ == "__main__":
    unittest.main()
