"""Delta membership tests use generated photos and mocked LS transport, not native acceptance."""
import copy
import shutil
from pathlib import Path

import unittest
from unittest.mock import patch
import test_guided_review as fixtures
from registry import CurationError, digest
import guided_review as guided
import intake


class IntakeTests(unittest.TestCase):
    start = fixtures.GuidedTests.start
    confirm = fixtures.GuidedTests.confirm
    tearDown = fixtures.GuidedTests.tearDown
    def setUp(self):
        fixtures.GuidedTests.setUp(self)
        view, draft = self.start()
        self.confirm(view, draft)
        self.new = self.base / 'new-capture'
        self.new.mkdir()
        from PIL import Image
        Image.new('RGB', (90, 60), (10, 20, 30)).save(self.new / 'incoming.png')
        self.before = guided.snapshot(self.registry, ['target'])
        self.old_links = self.registry.rows('SELECT * FROM object_assets WHERE object_id=? ORDER BY asset_id', ('target',))
        self.old_decisions = self.registry.rows('SELECT * FROM decisions ORDER BY id')

    def intake(self):
        view = intake.begin(self.registry, 'target', self.new)
        return guided.read(self.registry, view['id'], 'local')

    def test_add_only_new_photos_without_renewing_target_history(self):
        session = self.intake()
        self.assertEqual(len(session['assetIds']), 1)
        self.assertEqual(guided.snapshot(self.registry, ['target']), self.before)
        draft = copy.deepcopy(session['draft'])
        draft['photos'][0]['role'] = 'detail'
        saved = guided.save(self.registry, session, draft, 1)
        session = guided.read(self.registry, saved['id'], 'local')
        result = self.confirm(session, draft)
        self.assertEqual(result['state'], 'collected', result.get('error'))
        self.assertEqual(result['progress']['tasks'], 1)
        for old in self.old_links:
            self.assertEqual(dict(self.registry.db.execute('SELECT * FROM object_assets WHERE object_id=? AND asset_id=?', ('target', old['asset_id'])).fetchone()), old)
        for old in self.old_decisions:
            self.assertEqual(dict(self.registry.db.execute('SELECT * FROM decisions WHERE id=?', (old['id'],)).fetchone()), old)
        self.assertEqual(self.registry.db.execute("SELECT count(*) FROM proposals WHERE subject='target' AND kind='group'").fetchone()[0], 2)
        posts = self.native.posts
        self.assertEqual(self.confirm(session, draft)['state'], 'collected')
        self.assertEqual(posts, self.native.posts)

    def test_duplicate_bytes_only_add_occurrence(self):
        self.new.joinpath('incoming.png').unlink()
        old = self.registry.db.execute('SELECT relative_path FROM assets WHERE id=?', (self.old_links[0]['asset_id'],)).fetchone()[0]
        shutil.copyfile(self.source / old, self.new / 'copied.png')
        before = self.registry.db.execute('SELECT count(*) FROM assets').fetchone()[0]
        result = intake.begin(self.registry, 'target', self.new)
        self.assertEqual(result['status'], 'already_present')
        self.assertEqual(before, self.registry.db.execute('SELECT count(*) FROM assets').fetchone()[0])
        self.assertEqual(guided.snapshot(self.registry, ['target']), self.before)

    def test_stale_target_and_changed_source_fail_before_native_submission(self):
        session = self.intake()
        with self.registry.db:
            self.registry.db.execute("UPDATE object_presentation SET working_name='concurrent change' WHERE object_id='target'")
        posts = self.native.posts
        with self.assertRaisesRegex(CurationError, 'INTAKE_TARGET_STALE'):
            self.confirm(session, session['draft'])
        self.assertEqual(posts, self.native.posts)
        with self.registry.db:
            self.registry.db.execute("UPDATE object_presentation SET working_name='' WHERE object_id='target'")
        self.new.joinpath('incoming.png').write_bytes(b'changed generated bytes')
        with self.assertRaises(CurationError):self.confirm(session, session['draft'])
        self.assertEqual(posts, self.native.posts)

    def test_saved_session_reopens_and_uncertain_post_is_reconciled(self):
        session = self.intake()
        again = self.intake()
        self.assertEqual(session['id'], again['id'])
        self.native.lose_response = True
        failed = self.confirm(session, session['draft'])
        self.assertEqual(failed['state'], 'submitting')
        posts = self.native.posts
        result = self.confirm(session, session['draft'])
        self.assertEqual(result['state'], 'collected', result.get('error'))
        self.assertEqual(posts, self.native.posts)


    def test_partial_intake_second_review_retains_first_donor_and_membership(self):
        from PIL import Image
        Image.new('RGB', (90, 60), (40, 50, 60)).save(self.new / 'omitted.png')
        session = self.intake()
        draft = copy.deepcopy(session['draft'])
        draft['photos'][1]['destination'] = 'none'
        self.assertEqual(self.confirm(session, draft)['state'], 'collected')
        old = self.registry.rows('SELECT * FROM object_assets WHERE object_id=? ORDER BY asset_id', ('target',))
        donor = session['objectIds'][1]
        history = self.registry.rows('SELECT * FROM proposals WHERE subject=? ORDER BY id', (donor,))
        second = self.intake()
        self.assertNotEqual(second['objectIds'][1], donor)
        self.assertEqual(len(second['photos']), 1)
        self.assertEqual(self.registry.rows('SELECT * FROM proposals WHERE subject=? ORDER BY id', (donor,)), history)
        self.assertEqual(self.confirm(second, second['draft'])['state'], 'collected')
        for row in old:
            self.assertEqual(dict(self.registry.db.execute('SELECT * FROM object_assets WHERE object_id=? AND asset_id=?', ('target', row['asset_id'])).fetchone()), row)

    def test_stale_intake_can_restart_and_continue_outside_current_folder(self):
        first = self.intake()
        with self.registry.db:
            self.registry.db.execute("UPDATE object_presentation SET working_name='new name' WHERE object_id='target'")
        second = self.intake()
        self.assertNotEqual(first['id'], second['id'])
        self.assertTrue((self.registry.root / ('state/guided-review-' + first['id'] + '.json')).exists())
        self.assertEqual(guided.active(self.registry, 'local', ['target'])['id'], second['id'])
        self.assertEqual(self.confirm(second, second['draft'])['state'], 'collected')

    def test_selected_copy_changes_fail_even_with_intact_other_occurrence(self):
        self.registry.inspect(self.new, synthetic=False)
        backup = self.base / 'retained-copy';backup.mkdir()
        shutil.copyfile(self.new / 'incoming.png', backup / 'copy.png')
        self.registry.inspect(backup, synthetic=False)
        session = self.intake()
        (self.new / 'incoming.png').write_bytes(b'changed generated copy')
        posts = self.native.posts
        with self.assertRaises(CurationError):self.confirm(session, session['draft'])
        self.assertEqual(posts, self.native.posts)

    def test_collection_persistence_failure_retry_preserves_later_target_name(self):
        session = self.intake()
        real_persist = guided.persist
        failed = []
        def one_failure(registry, value):
            if value['state'] == 'collected' and not failed:
                failed.append(True)
                raise OSError('generated persistence failure')
            return real_persist(registry, value)
        with patch.object(guided, 'persist', side_effect=one_failure):
            self.confirm(session, session['draft'])
        with self.registry.db:
            self.registry.db.execute("UPDATE object_presentation SET working_name='later name' WHERE object_id='target'")
        reopened = guided.read(self.registry, session['id'], 'local')
        with self.assertRaisesRegex(CurationError, 'INTAKE_TARGET_STALE'):
            self.confirm(reopened, reopened['draft'])
        self.assertEqual(self.registry.db.execute("SELECT working_name FROM object_presentation WHERE object_id='target'").fetchone()[0], 'later name')

    def test_selected_files_are_bounded_and_cannot_escape(self):
        with self.assertRaises(CurationError):intake.selected_files(self.new, ['../escape.png'])
        with self.assertRaises(CurationError):intake.selected_files(self.new, ['incoming.png'] * 2)
        session = self.intake()
        bad = copy.deepcopy(session['draft']);bad['fields']['title']['action'] = 'set'
        with self.assertRaisesRegex(CurationError, 'INTAKE_EXISTING_FACTS_PRESERVED'):guided.save(self.registry, session, bad, 1)
